// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEDo3VnO148K6TRNYFklp21fn28C8FJ-s',
    appId: '1:898019114287:web:e15b03e47713da7c6b75da',
    messagingSenderId: '898019114287',
    projectId: 'inventory-app-4767e',
    authDomain: 'inventory-app-4767e.firebaseapp.com',
    storageBucket: 'inventory-app-4767e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhi4y4PmLlcXn4f0paE5iv4YuYEQYdaKg',
    appId: '1:898019114287:android:d1669f362d0bdf816b75da',
    messagingSenderId: '898019114287',
    projectId: 'inventory-app-4767e',
    storageBucket: 'inventory-app-4767e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsEL-DOghCDaC-QPix9Yt1kw8fD3H5Ox8',
    appId: '1:898019114287:ios:7e2ac8fc89695b256b75da',
    messagingSenderId: '898019114287',
    projectId: 'inventory-app-4767e',
    storageBucket: 'inventory-app-4767e.appspot.com',
    iosClientId: '898019114287-77uia0trs8scj3uljog3e8834unavefc.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsEL-DOghCDaC-QPix9Yt1kw8fD3H5Ox8',
    appId: '1:898019114287:ios:77432e7ab37066516b75da',
    messagingSenderId: '898019114287',
    projectId: 'inventory-app-4767e',
    storageBucket: 'inventory-app-4767e.appspot.com',
    iosClientId: '898019114287-gmmg1gtte8i5pgpq8k4kju8h4ddo4gom.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryapp.RunnerTests',
  );
}
